name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - run: 'terraform -chdir=terraform init'
      - run: 'terraform -chdir=terraform plan'

      - id: apply
        run: 'terraform -chdir=terraform apply -auto-approve'

      - id: ssapikeyraw
        run: echo "::set-output name=ssapikey::$(terraform -chdir=terraform output ssapikey)"
      - id: ssapikey
        run: echo "::set-output name=ssapikey::$(echo ${{ steps.ssapikeyraw.outputs.ssapikey }} )"

      - run: echo ${{ steps.ssapikey.outputs.ssapikey }}

      - name: Deploy static web app
        id: deploy-swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.ssapikey.outputs.ssapikey }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/app" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######